language: python
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install nmap

# command to run tests
script:
  #- pytest # or py.test for Python versions 3.5 and below

