language: python
sudo: false

python:
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  #- "3.7" not possible now
  #- "3.8" not possible now

# command to install dependencies
install:
  - pip install -r requirements.txt
  - sudo apt-get install nmap

# command to run tests
script:
  - pytest --doctest-modules -v --cov src --cov-report term-missing

after_success:
  - codecov  # Upload reports to codecov.io