language: python
sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"  # 3.7 development branch
  # - "3.7" not possible now
  #- "3.8" not possible now

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install python-coveralls # Install python-coveralls
  - sudo apt-get install nmap

# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below

after_success:
  - coveralls # Upload reports to coveralls.io
